name: Healthcare Data & ML Ingestion Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  run-etl-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Python Environment
      uses: actions/setup-python@v5
      with:
        python-python-version: '3.10'
        cache: 'pip'

    - name: Install System Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute ETL Data Streaming Layer
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python load.py

    - name: Execute Model Re-Training & Optimization Layer
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python train.py

    - name: Commit and Push Updated Artifacts (Model & Metadata)
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add healthcare_model.pkl
        # Sirf tab commit karega agar model file update hui hogi taake loop crash na ho
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-updated trained XGBoost model artifacts [Skip CI]" && git push)